### ISSUE TITLE
Where's the README?

### ISSUE THREAD

**Issue by vredchenko** [z0rc/dotfiles#1]
Hi.

Just wanted to point out I expected to see a few paragraphs in a README.md to quickly understand what's in this repo but there is not one...

BTW - welcome to the DataRobot team! Looking forward to meeting you in person :)

**Comment by z0rc** [comment]
Hi,

You're right, since there will be not only myself looking into this, I definitely should put some words into README. I'll update it soonish.

And thanks for warm greeting! :)
