### ISSUE TITLE
Describe common workflows

### ISSUE THREAD

**Issue by brianleppez** [z0rc/dotfiles#2709]
Hi z0rc, 

I've been a fan of your dotfiles for almost a year now and I've been using them as a base for my own. One thing that I spend a lot of time with is figuring out how you leverage all your plugins/tools to perform common developer/admin workflows. I'm interested to see how you use your dotfiles for:

- Git commit/push/rebase/diff
- Working with large codebases
- Searching files in a codebase
- common editing workflows
- how you use tmux + vim together

**Comment by z0rc** [comment]
Thanks! Sure thing.

> Git commit/push/rebase/diff

Plain git cli with small number of [abbreviations](https://github.com/z0rc/dotfiles/blob/master/zsh/plugins/abbreviations-store) that expand on input. It help to keep full command in history and more sensible, than aliases that can mean multiple things.

> Working with large codebases

Console file manager (ranger, mc), vim, [b]ag. I don't work much with really big codebases (like linux repo) actually, so ¯\\\_(ツ)_/¯.

> Searching files in a codebase

bag, fd, ocassionally fzf's widgets.

> common editing workflows

Have vim open in one terminal tab (I don't use tmux for local sessions) and testing in second terminal tab.

> how you use tmux + vim together

Most of the time I'm running tmux on remote machines to keep console session alive, vim in that case is used in and out to edit some files and that's it.
