### ISSUE TITLE
Removal of gutentags and tagbar

### ISSUE THREAD

**Issue by brianleppez** [z0rc/dotfiles#3164]
Hi z0rc, any reason why you decided to remove gutentags and tagbar? Are you replacing that functionality with something else?

Also, is there a better way to reach out to you other than through issues on your repo?

**Comment by z0rc** [comment]
In my case it was producing a lot of "garbage" tags when working with terraform, markdown and shell scripts. As of traditional programming languages LSP support is mature enough and well supported in Vim, to use it instead of tags.

> Also, is there a better way to reach out to you other than through issues on your repo?

I prefer to keep discussion about dotfiles in here.

**Comment by brianleppez** [comment]
I appreciate it, as always!
