### ISSUE TITLE
What's the reasoning behind manually installing tools?

### ISSUE THREAD

**Issue by brianleppez** [z0rc/dotfiles#945]
Why install `tmux`, `fzf`, etc, if they can be installed via the OS's package manager?

**Comment by z0rc** [comment]
`tmux` in fact isn't installed via these dotfiles.

`fzf` is different story. At the time I decided to include its feature to dotfiles, the package wasn't universally available in every common linux distribution. For example fzf isn't available in current Ubuntu LTS 18.04 in standard repos, see https://packages.ubuntu.com/search?keywords=fzf. Of course you can install fzf via PPA or similar measures. But my goal is to make dotfiles self contained, where you don't need to spend time on figuring out how to supply hard dependencies, which `fzf` became over time.
