### ISSUE TITLE
Typing is broken in tmux 

### ISSUE THREAD

**Issue by brianleppez** [z0rc/dotfiles#969]
Hi z0rc, been using your code a lot the past 4 days and I'm loving it so far. I can't seem to fix an issue where the typing is broken in `tmux`. Everything works fine opening using `zsh` inside `iTerm` but as soon as I open `tmux` the typing seems to be broken in `zsh`. I confirmed this by running `/bin/bash` inside `tmux` and it behaving appropriately. This is what I'm running into:

<img width="336" alt="Screen Shot 2020-03-17 at 3 37 33 PM" src="https://user-images.githubusercontent.com/5483606/76899490-ab1cd300-6865-11ea-9196-7c0603111a48.png">
Here I'm trying to type variations of the word `hello` and it seems like I can't get it to work. Do you have any guidance as to where the problem might lie? I can see this problem in apple Terminal as well.

**Comment by z0rc** [comment]
`terminals database is inaccessible` is a key here. Start looking into which version on ncurses database your tmux is built with. AFAIK macOS ships with quite old terminfo db, which doesn't have definition for `tmux-256color` TERM, it's set here https://github.com/z0rc/dotfiles/blob/master/tmux/tmux.conf#L5. 
Also check out https://superuser.com/questions/319912/i-cant-clear-the-terminal-in-mac-os-x-lion-terminals-database-is-inaccessibl and https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95.

**Comment by brianleppez** [comment]
> `terminals database is inaccessible` is a key here. Start looking into which version on ncurses database your tmux is built with. AFAIK macOS ships with quite old terminfo db, which doesn't have definition for `tmux-256color` TERM, it's set here https://github.com/z0rc/dotfiles/blob/master/tmux/tmux.conf#L5.
> Also check out https://superuser.com/questions/319912/i-cant-clear-the-terminal-in-mac-os-x-lion-terminals-database-is-inaccessibl and https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95.

Your second link worked wonderfully!
